<a href="https://colab.research.google.com/github/dewangsahuji/Cancer-pred/blob/main/TensorflowTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2.86,0,-3.5,8.25,90.65] , dtype=tf.float16)
print(tensor_one_d)

tf.Tensor([ 2.86  0.   -3.5   8.25 90.6 ], shape=(5,), dtype=float16)


In [ ]:
tensor_one_d = tf.constant([2.86,0,-3.5,8.25,90.65] , dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d , dtype=tf.int32)
print(casted_tensor_one_d)


tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2.86,0,-3.5,8.25,90.65] , dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d , dtype=tf.bool)
print(casted_tensor_one_d)

tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [ ]:
tensor_two_d = tf.constant(
    [
        [1,2,0],
        [3,5,-1],
        [1,5,6],
        [2,3,8]
    ]
)
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3,],
    dtype=tf.dtypes.int16,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]

 [[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]

 [[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]], shape=(3, 5, 5), dtype=int16)


In [ ]:
fill_tensor = tf.fill(
    [1,3,4], 5, name=None, layout=None
)
print(fill_tensor)


tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
ones_like_tensor = tf.ones_like(
    fill_tensor, dtype=None, name=None
)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
tensor_three_d = tf.constant(
    [
        [[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [10, 11, 12]],

        [[13, 14, 15],
        [16, 17, 18]],

        [[19, 20, 21],
        [22, 23, 24]]
    ]
)
print(tensor_three_d)
print(tensor_three_d.shape)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]], shape=(4, 2, 3), dtype=int32)
(4, 2, 3)


In [ ]:
tensor_three_d.shape

TensorShape([4, 2, 3])

In [ ]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [ ]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)  # 3


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]]])
tf.size(t)


<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
random_normal_tensor = tf.random.normal(
    shape=(3,2),
    mean = 0,
    stddev = 5,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
    )
print(random_normal_tensor)

tf.Tensor(
[[ 9.261613   6.6298227]
 [ 4.210775   3.034484 ]
 [-0.9514434  4.1530447]], shape=(3, 2), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)


tf.Tensor([85 95 82 62 97], shape=(5,), dtype=int32)


In [ ]:
tf.random.set_seed(10)
print(tf.random.uniform(shape=[3,] , maxval=5 , dtype=tf.int32 , seed=10))  # generates 'A3'
print(tf.random.uniform(shape=[3,] , maxval=5 , dtype=tf.int32 , seed=10))  # generates 'A3'
print(tf.random.uniform(shape=[3,] , maxval=5 , dtype=tf.int32 , seed=10))  # generates 'A3'
print(tf.random.uniform(shape=[3,] , maxval=5 , dtype=tf.int32 , seed=10))  # generates 'A3'
print(tf.random.uniform(shape=[3,] , maxval=5 , dtype=tf.int32 , seed=10))  # generates 'A3'



tf.Tensor([3 4 2], shape=(3,), dtype=int32)
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor([0 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 0], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(7)
print(tf.random.uniform(shape=[3,] , maxval=5 , dtype=tf.int32 , seed=10))  # generates 'A3'
print(tf.random.uniform(shape=[3,] , maxval=5 , dtype=tf.int32 , seed=10))  # generates 'A3'
print(tf.random.uniform(shape=[3,] , maxval=5 , dtype=tf.int32 , seed=10))  # generates 'A3'
print(tf.random.uniform(shape=[3,] , maxval=5 , dtype=tf.int32 , seed=10))  # generates 'A3'
print(tf.random.uniform(shape=[3,] , maxval=5 , dtype=tf.int32 , seed=10))  # generates 'A3'



tf.Tensor([3 2 4], shape=(3,), dtype=int32)
tf.Tensor([2 1 3], shape=(3,), dtype=int32)
tf.Tensor([4 4 4], shape=(3,), dtype=int32)
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor([2 1 3], shape=(3,), dtype=int32)


In [ ]:
tensor_four_d = tf.constant(
    [
        [
            [[ 1,  2,  3], [ 4,  5,  6]],
            [[ 7,  8,  9], [10, 11, 12]],
            [[13, 14, 15], [16, 17, 18]],
            [[19, 20, 21], [22, 23, 24]]
        ],
        [
            [[25, 26, 27], [28, 29, 30]],
            [[31, 32, 33], [34, 35, 36]],
            [[37, 38, 39], [40, 41, 42]],
            [[43, 44, 45], [46, 47, 48]]
        ],
        [
            [[49, 50, 51], [52, 53, 54]],
            [[55, 56, 57], [58, 59, 60]],
            [[61, 62, 63], [64, 65, 66]],
            [[67, 68, 69], [70, 71, 72]]
        ]
    ]
)
print(tensor_four_d)
print(tensor_four_d.shape)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]


 [[[25 26 27]
   [28 29 30]]

  [[31 32 33]
   [34 35 36]]

  [[37 38 39]
   [40 41 42]]

  [[43 44 45]
   [46 47 48]]]


 [[[49 50 51]
   [52 53 54]]

  [[55 56 57]
   [58 59 60]]

  [[61 62 63]
   [64 65 66]]

  [[67 68 69]
   [70 71 72]]]], shape=(3, 4, 2, 3), dtype=int32)
(3, 4, 2, 3)


# Tensor Initialization and Casting Indexing

In [ ]:
tensor_indexed = tf.constant([6,7,2,4,6,66,7])

print(tensor_indexed)
print(tensor_indexed[:4])
print(tensor_indexed[2:])

tf.Tensor([ 6  7  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([6 7 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 2  4  6 66  7], shape=(5,), dtype=int32)


In [ ]:
print(tensor_two_d[0:3 , 0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [ ]:
x_1 = tf.constant([5,3,2,4,5,8,9] ,dtype=tf.float32)
x_2 = tf.constant([5,3,2,4,5,0,9] ,dtype=tf.float32)

print(tf.math.divide_no_nan(x_1,x_2))



tf.Tensor([1. 1. 1. 1. 1. 0. 1.], shape=(7,), dtype=float32)


In [ ]:
x_1 = tf.constant([5,3,2,4,5,8,9] ,dtype=tf.float32)
x_2 = tf.constant([[4],[5],[5]] ,dtype=tf.float32)

print(tf.math.maximum(x_1,x_2))




tf.Tensor(
[[5. 4. 4. 4. 5. 8. 9.]
 [5. 5. 5. 5. 5. 8. 9.]
 [5. 5. 5. 5. 5. 8. 9.]], shape=(3, 7), dtype=float32)


In [ ]:
x_argmax = tf.constant( [[100, 2, 3, 4, 5],
                         [6, 7, 4890, 9, 1012],
                         [11, 12, 13, 14, 15]])

print(tf.math.argmax(x_argmax , axis=1))

tf.Tensor([0 2 4], shape=(3,), dtype=int64)


In [ ]:
tensor_two_d

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  0],
       [ 3,  5, -1],
       [ 1,  5,  6],
       [ 2,  3,  8]], dtype=int32)>

In [ ]:
print(tf.reduce_mean(
    tensor_two_d,
    axis=1,
    keepdims=False,
    name=None
))

tf.Tensor([1 2 4 4], shape=(4,), dtype=int32)


In [ ]:
print(tf.reduce_mean(
    tensor_two_d,
    axis=1,
    keepdims=True,
    name=None
))

tf.Tensor(
[[1]
 [2]
 [4]
 [4]], shape=(4, 1), dtype=int32)


In [ ]:
x_1 = tf.constant([[1, 2, 3],
                   [4, 5, 6]])

x_2 = tf.constant([[7, 8],
                   [9, 10],
                   [11, 12]])
print(tf.linalg.matmul(x_2,x_1))

tf.Tensor(
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]], shape=(3, 3), dtype=int32)


In [ ]:
x_1@x_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tensor_two_d = tf.constant(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], dtype=tf.float32
)
print(tensor_two_d)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)


In [ ]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
tf.linalg.svd(tensor_two_d)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.6848103e+01, 1.0683687e+00, 3.0203776e-07], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.21483706,  0.8872304 ,  0.40824872],
        [-0.5205873 ,  0.24964428, -0.8164965 ],
        [-0.8263374 , -0.38794297,  0.40824813]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.47967124, -0.7766908 ,  0.40824857],
        [-0.5723677 , -0.07568675, -0.81649655],
        [-0.6650644 ,  0.6253182 ,  0.40824804]], dtype=float32)>)

## **Ragged** **Tensors**

In [ ]:
tensor_two_d = [[1,2,0],
                [3,],
                [1,5,6,5,6],
                [2,3]]

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged)


<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


## Sparse Tensors


In [ ]:
tensor_sparse = tf.sparse.SparseTensor(
    indices=[[1,1], [3,4]],
    values=[11, 23],
    dense_shape=[5, 6]
)
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 23], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [ ]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 23,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

## String Tensors

In [ ]:
tensor_string = tf.constant(["Tensorflow", "Deep Learning", "AI"])
print(tensor_string)

tf.Tensor([b'Tensorflow' b'Deep Learning' b'AI'], shape=(3,), dtype=string)


In [ ]:
tf.strings.join(tensor_string , separator="+")


<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow+Deep Learning+AI'>

# Variables

In [ ]:
x = tf.constant([1,2])

In [ ]:
x_var = tf.Variable(x)
print(x_var)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>
